### ISSUE TITLE
App installation issues

### ISSUE THREAD

**Issue by moliri** [NUDelta/CrowdCheer#6]
some iPhone 5 users couldn't use the app: 
1. it crashed as soon as you loaded it
2. it reported that it could not be installed

**Comment by MattCheetham** [comment]
Looks like you're trying to use HealthKit on iOS 7 which causes  crash.

Presume the iPhone 5 users reporting the crash on launch are iOS 7 users. See error below.

```
dyld: Library not loaded: /System/Library/Frameworks/HealthKit.framework/HealthKit
  Referenced from: /Users/matthewcheetham/Library/Developer/CoreSimulator/Devices/273D298E-A8EB-4F76-8F5F-B4B3817E57E2/data/Applications/D18B6D5E-979D-4EEC-AA25-A448D942FCEA/CrowdCheer.app/CrowdCheer
  Reason: image not found
(lldb) 
```

**Comment by moliri** [comment]
Removed HealthKit framework and tested on iOS 7 - looks like it doesn't crash anymore. Thanks @MattCheetham!
